package com.example.demo;

import com.example.demo.estructuraClientes.Cliente;
import com.example.demo.estructuraClientes.registroClientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patrick
 */
public class registrarClientes extends javax.swing.JFrame {

    registroClientes lista = new registroClientes();
    static DefaultTableModel md;
    String data[][] = {};
    String Detalles[] = {"cédula", "nombre", "fecha de nacimiento", "correo", "categoría"};

    public registrarClientes() {
        initComponents();
        md = new DefaultTableModel(data, Detalles);
        tabla.setModel(md);
    }

    public registrarClientes(registroClientes listaC) {
        this.lista = listaC;
        initComponents();
        
       /*
        int cedula = lista.getInfo().getValue().getCedula();
        String nombre = lista.getInfo().getValue().getNombre();
        String fechaNaci = lista.getInfo().getValue().getFecha_nacimiento();
        String correo = lista.getInfo().getValue().getCorreo();
        String categoria = lista.getInfo().getValue().getCategoria();*/
        
        /*Object datos[] = {cedula, nombre, fechaNaci, correo, categoria};
        md.addRow(datos);*/
        md = new DefaultTableModel(data, Detalles);
        tabla.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnEditarRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnOrdenAlq = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        jComboCategoria = new javax.swing.JComboBox<>();
        btnVerRegistro = new javax.swing.JButton();
        txtFechaNaci = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnEliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("FECHA DE NACIMIENTO:");

        btnEditarRegistro.setBackground(new java.awt.Color(204, 204, 255));
        btnEditarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarRegistro.setText("EDITAR CAMPOS");
        btnEditarRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegistroActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("HENZ RENT A CAR");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE CLIENTE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CÉDULA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NOMBRE:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("CORREO:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CATEGORÍA:");

        btnOrdenAlq.setBackground(new java.awt.Color(102, 102, 255));
        btnOrdenAlq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOrdenAlq.setText("CREAR ORDEN \nDE ALQUILER");
        btnOrdenAlq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOrdenAlq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenAlqActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "MARCA", "TIPO", "MODELO", "AÑO", "COLOR", "PASAJEROS", "COMBUSTIBLE"
            }
        ));
        tabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabla);

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR CLIENTE");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jComboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA OPCIÓN", "Bronce", "Plata", "Oro", "Zafiro" }));
        jComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaActionPerformed(evt);
            }
        });

        btnVerRegistro.setBackground(new java.awt.Color(204, 204, 255));
        btnVerRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerRegistro.setText("CONSULTAR POR CÉDULA");
        btnVerRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistroActionPerformed(evt);
            }
        });

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaFocusGained(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        btnEliminarRegistro.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarRegistro.setText("ELIMINAR CLIENTE");
        btnEliminarRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnOrdenAlq, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(98, 98, 98)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(83, 83, 83)
                                    .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGap(340, 340, 340)))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrdenAlq, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegistroActionPerformed
        String cedulaBuscada = JOptionPane.showInputDialog("Ingrese el número de cédula del cliente a eliminar.");

        if (cedulaBuscada.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el número de cédula.");

        } else if (!cedulaBuscada.matches("[0-9]+") || cedulaBuscada.length() < 9 || cedulaBuscada.length() > 9) {
            JOptionPane.showMessageDialog(null, "Por favor digite un número de cédula válido. "
                    + "\nNo use ningún tipo de signo para separar los números y recuerde ingresar 9 números.");
        } else {
            modificacionCliente ventanaMod = new modificacionCliente(Integer.parseInt(cedulaBuscada), this.lista);
            ventanaMod.setTitle("Modificación de cliente");
            ventanaMod.setLocationRelativeTo(null);
            ventanaMod.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnEditarRegistroActionPerformed

    private void btnOrdenAlqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenAlqActionPerformed
      
        Orden Registro = new Orden();
      Registro.setVisible(true);

    }//GEN-LAST:event_btnOrdenAlqActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String fechaNaci = txtFechaNaci.getText();
        String correo = txtCorreo.getText();
        String categoria = (String) jComboCategoria.getSelectedItem();

        if (this.txtCedula.getText().equals("") && this.txtNombre.getText().equals("")
                && this.txtFechaNaci.getText().equals("") && this.jComboCategoria.getSelectedItem().equals("SELECCIONE UNA OPCIÓN")) {
            JOptionPane.showMessageDialog(null, "Informacion Incompleta");

        } else if (this.txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informacion Incompleta. Por favor ingrese el nombre del cliente.");

        } else if (this.txtCedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informacion Incompleta. Por favor ingrese el número de cédula.");

        } else if (this.txtFechaNaci.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informacion Incompleta. Por favor ingrese la fecha de nacimiento.");

        } else if (this.jComboCategoria.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Informacion Incompleta. Por favor elija una categoría.");

        } else if (this.txtNombre.getText().matches(".*[0-9].*")) {
            JOptionPane.showMessageDialog(null, "Por favor digite un nombre válido.");
            //this.txtNombre.setText("");

        } else if (!this.txtCedula.getText().matches("[0-9]+") || this.txtCedula.getText().length() < 9 || this.txtCedula.getText().length() > 9) {
            JOptionPane.showMessageDialog(null, "Por favor digite un número de cédula válido. "
                    + "\nNo use ningún tipo de signo para separar los números y recuerde ingresar 9 números.");
            //this.txtCedula.setText("");

        } else if (!this.txtFechaNaci.getText().matches("^([0-2][0-9]|3[0-1])(\\/)(0[1-9]|1[0-2])\\2(\\d{4})$")) {
            JOptionPane.showMessageDialog(null, "Por favor digite una fecha válida. \nUtilice solamente \"/\" para separación y siga el formato dd/mm/yyyy. ");
            //this.txtFechaNaci.setText("");

        } else if (this.txtCorreo.getText().matches("^[\\w-+]+(\\.[\\w-]{1,62}){0,126}@[\\w-]{1,63}(\\.[\\w-]{1,62})+/[\\w-]+$")) {
            JOptionPane.showMessageDialog(null, "Por favor digite una dirección de correo electrónico válido.");
            //this.txtCorreo.setText("");

        } else {
            Cliente info = new Cliente(Integer.parseInt(cedula), nombre, fechaNaci, correo, categoria);
            lista.registrar(info);

            Object datos[] = {cedula, nombre, fechaNaci, correo, categoria};
            md.addRow(datos);

            //lista.mostrarRegistros();
            JOptionPane.showMessageDialog(null, "Informacion guardada satisfactoriamente");
            limpiarCajas();

        }
    }

    private void limpiarCajas() {
        this.txtCedula.setText("");
        this.txtNombre.setText("");
        this.txtFechaNaci.setText("");
        this.txtCorreo.setText("");
        this.jComboCategoria.setSelectedIndex(0);
    }

    //con eso se crea el fichero txt y se guarda localmente en documentos
    public void guardarInfo() {
        /*try {
            FileOutputStream file = new FileOutputStream("REGISTRO.txt");
            ObjectOutputStream obj2 = new ObjectOutputStream(file);
            obj2.writeObject(arreglo);
            obj2.close();

            JOptionPane.showMessageDialog(null, "La reservación se guardó satisfactoriamente");
        } catch (FileNotFoundException ex) {

            JOptionPane.showMessageDialog(rootPane, "Se generó un problema con el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {

            JOptionPane.showMessageDialog(rootPane, "Se generó un problema con el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }*/

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCategoriaActionPerformed

    private void btnVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistroActionPerformed
        String cedulaBuscada = JOptionPane.showInputDialog("Ingrese el número de cédula del cliente a editar.");

        if (cedulaBuscada.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el número de cédula.");

        } else if (!cedulaBuscada.matches("[0-9]+") || cedulaBuscada.length() < 9 || cedulaBuscada.length() > 9) {
            JOptionPane.showMessageDialog(null, "Por favor digite un número de cédula válido. "
                    + "\nNo use ningún tipo de signo para separar los números y recuerde ingresar 9 números.");
        } else {

            lista.consultarCliente(Integer.parseInt(cedulaBuscada));

            if (lista.getInfo() != null) {
                JOptionPane.showMessageDialog(null, lista.getInfo().getValue().toString());
            }
        }
    }//GEN-LAST:event_btnVerRegistroActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaFocusGained

    private void btnEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegistroActionPerformed
        String cedulaBuscada = JOptionPane.showInputDialog("Ingrese el número de cédula del cliente a eliminar.");

        if (cedulaBuscada.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el número de cédula.");

        } else if (!cedulaBuscada.matches("[0-9]+") || cedulaBuscada.length() < 9 || cedulaBuscada.length() > 9) {
            JOptionPane.showMessageDialog(null, "Por favor digite un número de cédula válido. "
                    + "\nNo use ningún tipo de signo para separar los números y recuerde ingresar 9 números.");
        } else {

            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que quiere eliminar el registro del cliente con la cédula "
                    + cedulaBuscada + "?", "YES_NO_OPTION", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                lista.eliminarCliente(Integer.parseInt(cedulaBuscada));

            }

        }
    }//GEN-LAST:event_btnEliminarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarRegistro;
    private javax.swing.JButton btnEliminarRegistro;
    private javax.swing.JButton btnOrdenAlq;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVerRegistro;
    private javax.swing.JComboBox<String> jComboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNaci;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
